// L2 Chain configurations with RPC endpoints
export interface L2Chain {
  id: string
  name: string
  shortName?: string
  rpcUrl: string
  chainId: number
  nativeCurrency: string
  website?: string
  l2BeatSlug?: string
  category: 'rollup' | 'validium' | 'l1'
  isFullRollup: boolean // Uses Ethereum for DA
  icon?: string
}

export const L2_CHAINS: L2Chain[] = [
  {
    id: 'ethereum',
    name: 'Ethereum',
    rpcUrl: 'https://eth.llamarpc.com',
    chainId: 1,
    nativeCurrency: 'ETH',
    website: 'https://ethereum.org',
    category: 'l1',
    isFullRollup: false,
    icon: 'https://icons.llamao.fi/icons/chains/rsz_ethereum.jpg',
  },
  {
    id: 'arbitrum',
    name: 'Arbitrum One',
    shortName: 'Arbitrum',
    rpcUrl: 'https://arb1.arbitrum.io/rpc',
    chainId: 42161,
    nativeCurrency: 'ETH',
    website: 'https://arbitrum.io',
    l2BeatSlug: 'arbitrum',
    category: 'rollup',
    isFullRollup: true,
    icon: 'https://icons.llamao.fi/icons/chains/rsz_arbitrum.jpg',
  },
  {
    id: 'optimism',
    name: 'OP Mainnet',
    shortName: 'Optimism',
    rpcUrl: 'https://mainnet.optimism.io',
    chainId: 10,
    nativeCurrency: 'ETH',
    website: 'https://optimism.io',
    l2BeatSlug: 'optimism',
    category: 'rollup',
    isFullRollup: true,
    icon: 'https://icons.llamao.fi/icons/chains/rsz_optimism.jpg',
  },
  {
    id: 'base',
    name: 'Base',
    rpcUrl: 'https://mainnet.base.org',
    chainId: 8453,
    nativeCurrency: 'ETH',
    website: 'https://base.org',
    l2BeatSlug: 'base',
    category: 'rollup',
    isFullRollup: true,
    icon: 'https://icons.llamao.fi/icons/chains/rsz_base.jpg',
  },
  {
    id: 'zksync-era',
    name: 'zkSync Era',
    shortName: 'zkSync',
    rpcUrl: 'https://mainnet.era.zksync.io',
    chainId: 324,
    nativeCurrency: 'ETH',
    website: 'https://zksync.io',
    l2BeatSlug: 'zksync-era',
    category: 'rollup',
    isFullRollup: true,
    icon: 'https://icons.llamao.fi/icons/chains/rsz_zksync-era.jpg',
  },
  {
    id: 'polygon-zkevm',
    name: 'Polygon zkEVM',
    shortName: 'Polygon zk',
    rpcUrl: 'https://zkevm-rpc.com',
    chainId: 1101,
    nativeCurrency: 'ETH',
    website: 'https://polygon.technology/polygon-zkevm',
    l2BeatSlug: 'polygonzkevm',
    category: 'rollup',
    isFullRollup: true,
    icon: 'https://icons.llamao.fi/icons/chains/rsz_polygon.jpg',
  },
  {
    id: 'linea',
    name: 'Linea',
    rpcUrl: 'https://rpc.linea.build',
    chainId: 59144,
    nativeCurrency: 'ETH',
    website: 'https://linea.build',
    l2BeatSlug: 'linea',
    category: 'rollup',
    isFullRollup: true,
    icon: 'https://icons.llamao.fi/icons/chains/rsz_linea.jpg',
  },
  {
    id: 'scroll',
    name: 'Scroll',
    rpcUrl: 'https://rpc.scroll.io',
    chainId: 534352,
    nativeCurrency: 'ETH',
    website: 'https://scroll.io',
    l2BeatSlug: 'scroll',
    category: 'rollup',
    isFullRollup: true,
    icon: 'https://icons.llamao.fi/icons/chains/rsz_scroll.jpg',
  },
  {
    id: 'starknet',
    name: 'Starknet',
    rpcUrl: 'https://starknet-mainnet.public.blastapi.io',
    chainId: 0, // Starknet doesn't use standard chainId
    nativeCurrency: 'ETH',
    website: 'https://starknet.io',
    l2BeatSlug: 'starknet',
    category: 'rollup',
    isFullRollup: true,
    icon: 'https://icons.llamao.fi/icons/chains/rsz_starknet.jpg',
  },
  {
    id: 'mantle',
    name: 'Mantle',
    rpcUrl: 'https://rpc.mantle.xyz',
    chainId: 5000,
    nativeCurrency: 'MNT',
    website: 'https://mantle.xyz',
    l2BeatSlug: 'mantle',
    category: 'validium',
    isFullRollup: false, // Uses own DA
    icon: 'https://icons.llamao.fi/icons/chains/rsz_mantle.jpg',
  },
  {
    id: 'manta',
    name: 'Manta Pacific',
    shortName: 'Manta',
    rpcUrl: 'https://pacific-rpc.manta.network/http',
    chainId: 169,
    nativeCurrency: 'ETH',
    website: 'https://manta.network',
    l2BeatSlug: 'mantapacific',
    category: 'validium',
    isFullRollup: false,
    icon: 'https://icons.llamao.fi/icons/chains/rsz_manta.jpg',
  },
  {
    id: 'blast',
    name: 'Blast',
    rpcUrl: 'https://rpc.blast.io',
    chainId: 81457,
    nativeCurrency: 'ETH',
    website: 'https://blast.io',
    l2BeatSlug: 'blast',
    category: 'rollup',
    isFullRollup: true,
    icon: 'https://icons.llamao.fi/icons/chains/rsz_blast.jpg',
  },
  {
    id: 'mode',
    name: 'Mode',
    rpcUrl: 'https://mainnet.mode.network',
    chainId: 34443,
    nativeCurrency: 'ETH',
    website: 'https://mode.network',
    l2BeatSlug: 'mode',
    category: 'rollup',
    isFullRollup: true,
    icon: 'https://icons.llamao.fi/icons/chains/rsz_mode.jpg',
  },
  {
    id: 'zora',
    name: 'Zora',
    rpcUrl: 'https://rpc.zora.energy',
    chainId: 7777777,
    nativeCurrency: 'ETH',
    website: 'https://zora.co',
    l2BeatSlug: 'zora',
    category: 'rollup',
    isFullRollup: true,
    icon: 'https://icons.llamao.fi/icons/chains/rsz_zora.jpg',
  },
]
